name: Publish released version

on:
  release:
    types: [published]

jobs:
  publish-amd64:
    runs-on: ubuntu-24.04
    name: "Publish for AMD64"

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimit
          tag-pattern: /^v([0-9.]+)$/
          latest-on-tag: true
          restrict-to: openzim/zimit
          registries: ghcr.io
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
          platforms: |
            linux/amd64

  # Disabled for now, see https://github.com/openzim/zimit/issues/463
  # publish-arm64:
  #   runs-on: ubuntu-24.04
  #   name: "Publish for ARM64"
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Build and push Docker image
  #       uses: openzim/docker-publish-action@v10
  #       with:
  #         image-name: openzim/zimit
  #         tag-pattern: /^v([0-9.]+)$/
  #         latest-on-tag: true
  #         restrict-to: openzim/zimit
  #         registries: ghcr.io
  #         credentials: |
  #           GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
  #           GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
  #         repo_description: auto
  #         repo_overview: auto
  #         platforms: |
  #           linux/arm64
